name: Terraform Deployment

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

env:
  AWS_REGION: 'us-east-1'

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      tf_directory: ${{ steps.set-env.outputs.tf_directory }}
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set environment (dev or prod)
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Environment es prod"
            echo "environment=prod" >> $GITHUB_ENV
            echo "tf_directory=environments/prod" >> $GITHUB_ENV
            echo "::set-output name=tf_directory::environments/prod"
            echo "::set-output name=environment::prod"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "Environment es dev"
            echo "environment=dev" >> $GITHUB_ENV
            echo "tf_directory=environments/dev" >> $GITHUB_ENV
            echo "::set-output name=tf_directory::environments/dev"
            echo "::set-output name=environment::dev"
          fi

  install-terraform:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

  terraform-validate:
    runs-on: ubuntu-latest
    needs: install-terraform
    steps:
      - name: Terraform Validate
        run: |
          cd ${{ needs.set-environment.outputs.tf_directory }}
          terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-test:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Terraform Test
        run: |
          cd ${{ needs.set-environment.outputs.tf_directory }}
          terraform plan -detailed-exitcode
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-test
    steps:
      - name: Terraform Plan
        run: |
          cd ${{ needs.set-environment.outputs.tf_directory }}
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/master'  # Solo ejecutar en producción
    steps:
      - name: Terraform Apply
        run: |
          cd ${{ needs.set-environment.outputs.tf_directory }}
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
